### ISSUE TITLE
Boot VitaHEX logo question.

### ISSUE THREAD

**Issue by euandersson** [VitaHEX-Games/HexFlow-Launcher#11]
It's possible change the the boot logo image of this amazing app ? Turn off or something, i tried direct on folders, 8bit PNG but nothing, thx again.

**Comment by VitaHEX-Games** [comment]
I don't think it is possible, the pic0 file is protected.
Do you suggest any better startup image?

**Comment by euandersson** [comment]
All black or PS logo like the psvita boot screen, make more sense when we use the app combined with autoboot plugin.
