### ISSUE TITLE
Error 157

### ISSUE THREAD

**Issue by Jimijo1** [VitaHEX-Games/HexFlow-Launcher#2]
Hello, I have installed HEX-Launcher and when I start I get a black screen and the text "157: error opening SFO file".
What can be?

Greetings.

**Comment by VitaHEX-Games** [comment]
**Temporary solution:**
Edit the "index.lua" file located at "ux0:app/HXFL00001/" and comment or delete the two lines 157 and 158.

**Comment by Jimijo1** [comment]
**Edit the "index.lua" file located at "ux0:app/HXFL00001/" and comment or delete the two lines 157 and 158.**

Thanks for answering! I have tried to do what you tell me but I cannot find line 157 and 158
