### ISSUE TITLE
[string"?"]:307: attempt to index a nil value

### ISSUE THREAD

**Issue by ace119922** [VitaHEX-Games/HexFlow-Launcher#4]
Good Day, I'm having this error when changing categories, it appears after HOMEBREWS category .

**Comment by NeonLightning** [comment]
same thing happened here.

**Comment by VitaHEX-Games** [comment]
Have you tried the latest v0.2.1 hotfix release?

**Comment by VitaHEX-Games** [comment]
> 
> 
> Good Day, I'm having this error when changing categories, it appears after HOMEBREWS category .

Have you tried the latest v0.2.1 hotfix release?

**Comment by ace119922** [comment]
hey sorry for the late reply just got time to install the hotfix and it worked, thanks, and sorry don't know why I didn't look here first was using Homebrew Browser

**Comment by NeonLightning** [comment]
same problem here lol vhbb
