### ISSUE TITLE
PS1 trying to extend screen crash

### ISSUE THREAD

**Issue by LehmannADL** [VitaHEX-Games/HexFlow-Launcher#41]
Essentially, whenever i access the official settings the app/game crashes with a C2-12828-1 Error. 

Happy to Cashapp/paypal 10-20$ for a resolution.

**Comment by BlackSheepBoy69** [comment]
Please find the file "ux0:data/HexFlow/config.dat" from your vita, send it to your computer (via USB) and upload it to mediafire, then send me the mediafire link for analysis. You could also try to delete that config.dat and see if that fixes it.

**Comment by BlackSheepBoy69** [comment]
Hello, please provide more details. "trying to extend screen" Do you mean the triangle menu? "access the official settings" Do you mean the start menu? What are we talking about exactly. If it's the triangle menu, is it only on certain games, and if it is, what is the game name and if you know (it's fine if you don't) what the game ID is?... for example: SLUS12345.

**Comment by LehmannADL** [comment]
launcher: latest 0.5

i launch hex/ go to  ps1/ launch any ps1 game (i use Einhander/SCUS-94243)/ game starts/ Hold PS button/ Settings/ CRASH Error code C2-12828-1.

**Comment by LehmannADL** [comment]
btw when it crashes it semi hard locks the system. you can move around and quit apps but nothing will launch. you cant restart so you have to hard reset the vita.

**Comment by BlackSheepBoy69** [comment]
Does the game run fine or why are you holding PS button? I think I might know a way to fix this but I need to know if the game runs fine or not (before the ps button crash).

**Comment by LehmannADL** [comment]
yes it does run fine.

**Comment by BlackSheepBoy69** [comment]
Go to Adrenaline Bubble Manager and press circle to open the individual edit menu. Scroll down to Einhander and press triangle to open the "Edit boot.bin" menu. Press down 3 times so you're where it says "PSBUTTON MODE" and press right once and it should say "PSBUTTON MODE: LIVEAREA". Press triangle for "Done editing" and wait 5 seconds, then close out of Adrenaline Bubble Manager and try Einhander again.

**Comment by LehmannADL** [comment]
it actually has nothing to do with you and your software i figured it out thank you for trying to help anyways.

**Comment by BlackSheepBoy69** [comment]
Dare I ask what was the issue?

**Comment by LehmannADL** [comment]
Uninstalling rescaler!
