### ISSUE TITLE
Future request - categorise by PSP / PSX by original game ID

### ISSUE THREAD

**Issue by jimbob4000** [VitaHEX-Games/HexFlow-Launcher#5]
At the moment PSP games seem to be categorised by the pspemu prefix.

Categorising by the original game ID would allow for automatic cover matching and separate PSP and PSX categories. 

Game title (ID) can be selected as an export option using Adrenaline Bubbles Manager.

**Comment by VitaHEX-Games** [comment]
Should be addressed in v0.4
