### ISSUE TITLE
ERROR sfo is corrupted

### ISSUE THREAD

**Issue by funtoicy** [VitaHEX-Games/HexFlow-Launcher#6]
Sfo is corrupted

**Comment by VitaHEX-Games** [comment]
Can you specify which game/app is causing this error?

**Comment by funtoicy** [comment]
The launcher itself, i won't work.

**Comment by VitaHEX-Games** [comment]
I will need more information. Is this the latest release (v0.3.1)? Also a screenshot of the error message would help.

**Comment by funtoicy** [comment]
Yes it is the lastest
![Uploading IMG_20201113_164136.jpg…]()

**Comment by funtoicy** [comment]
The image will not upload but it says "string"?" 242 the sfo file is corrupted"

**Comment by VitaHEX-Games** [comment]
Are you using SD2Vita? The app supports games from ux0 partition only.
