### ISSUE TITLE
Feature request - Option to disable homebrew apps

### ISSUE THREAD

**Issue by jimbob4000** [VitaHEX-Games/HexFlow-Launcher#7]
An option to disable homebrew apps would be awesome, would result in a clean listing of boxed PlayStation retail releases across the various consoles. 

Disabling would hide scanned results form "All" category and would also hide the "homebrew" category.

**Comment by VitaHEX-Games** [comment]
Added in version 0.5

**Comment by jimbob4000** [comment]
Thanks for implementing the option.
It could be taken one step further to prevent homebrews showing in the all category.

Working code below:

````
-- Scan Homebrews
if showHomebrews == 1 then -- Scan Homebrews
table.insert(folders_table, file)
--table.insert(homebrews_table, file)
custom_path = covers_psv .. app_title .. ".png"
custom_path_id = covers_psv .. file.name .. ".png"
file.app_type=0
else -- Don't scan Homebrews
end
````
